using DataTransferObjects;
using LogicLayer;
using LogicLayerInterfaces;
using System;
using System.Windows;
using System.Windows.Controls;

namespace WPFPresentationLayer.RecruitingPages
{
    /// <summary>
    /// Interaction logic for ListAllEvents.xaml
    /// 
    /// CREATOR: Steve Coonrod
    /// CREATED: 3\08\2020
    /// APPROVER: Ryan Morganti
    /// 
    /// This is the page for displaying the list of ALL Events in the DB
    /// This is ADMIN and DC roles only
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// UPDATER: NA
    /// UPDATED: NA
    /// UPDATE: NA
    /// 
    /// </remarks>
    public partial class ListAllEvents : Page
    {
        private IPUEventManager _eventManager = null;//For using event manager methods
        private EventMgmt _eventMgmt = null;//For allowing the updating of the EventMgmt page's _selectedEvent

        /// <summary>
        /// 
        /// CREATOR: Steve Coonrod
        /// CREATED: 3\08\2020
        /// APPROVER: Ryan Morganti
        /// 
        /// A no-argumnet constructor. For some reason it is necessary for the programs initialization
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// UPDATER: NA
        /// UPDATED: NA
        /// UPDATE: NA
        /// 
        /// </remarks>
        public ListAllEvents()
        {
            _eventManager = new PUEventManager();
            InitializeComponent();
        }

        /// <summary>
        /// 
        /// CREATOR: Steve Coonrod
        /// CREATED: 3\08\2020
        /// APPROVER: Ryan Morganti
        /// 
        /// The constructor for this page.
        /// Takes as parameters the current Event Manager and EventMgmt page
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// UPDATER: NA
        /// UPDATED: NA
        /// UPDATE: NA
        /// 
        /// </remarks>
        /// <param name="eventManager"></param>
        /// <param name="eventMgmt"></param>
        public ListAllEvents(IPUEventManager eventManager, EventMgmt eventMgmt)
        {
            _eventManager = eventManager;
            _eventMgmt = eventMgmt;
            InitializeComponent();
        }

        /// <summary>
        /// 
        /// CREATOR: Steve Coonrod
        /// CREATED: 3\08\2020
        /// APPROVER: Ryan Morganti
        /// 
        /// This is a handler for the datagrid, to hide unwanted fields
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// UPDATER: NA
        /// UPDATED: NA
        /// UPDATE: NA
        /// 
        /// </remarks>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void dgEventList_All_AutoGeneratedColumns(object sender, EventArgs e)
        {
            dgEventList_All.Columns.RemoveAt(10);
            dgEventList_All.Columns.RemoveAt(2);
            dgEventList_All.Columns.RemoveAt(1);
            dgEventList_All.Columns.RemoveAt(0);
            dgEventList_All.Columns[1].Header = "Type";
            dgEventList_All.Columns[2].Header = "Date and Time";
            dgEventList_All.Columns[dgEventList_All.Columns.Count - 2].DisplayIndex = 2;
            dgEventList_All.Columns[dgEventList_All.Columns.Count - 1].Width =
                new DataGridLength(1, DataGridLengthUnitType.Star);

        }


        /// <summary>
        /// 
        /// CREATOR: Steve Coonrod
        /// CREATED: 3\08\2020
        /// APPROVER: Ryan Morganti
        /// 
        /// This is an event handler for when the datagrid is loaded
        /// Retrieves its item source from the DB through the event manager
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// UPDATER: NA
        /// UPDATED: NA
        /// UPDATE: NA
        /// 
        /// </remarks>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void dgEventList_All_Loaded(object sender, RoutedEventArgs e)
        {
            try
            {
                if (dgEventList_All.ItemsSource == null)
                {
                    dgEventList_All.ItemsSource = _eventManager.GetAllEvents();
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message, ex.InnerException.Message);
            }

        }

        /// <summary>
        /// 
        /// CREATOR: Steve Coonrod
        /// CREATED: 3\08\2020
        /// APPROVER: Ryan Morganti
        /// 
        /// This is the event handler for the datagrids selection_changed event
        /// This sets the EventMgmt page's _selectedEvent value to the datagrids selected item
        /// Then toggles the buttons that rely on an event being selected
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// UPDATER: NA
        /// UPDATED: NA
        /// UPDATE: NA
        /// 
        /// </remarks>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void dgEventList_All_SelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            _eventMgmt._selectedEvent = (PUEvent)dgEventList_All.SelectedItem;
            _eventMgmt.ToggleEventButtons();
        }
    }
}
