using DataTransferObjects;
using LogicLayerInterfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;

namespace WPFPresentationLayer.PersonnelPages
{
    /// <summary>
    /// Interaction logic for frmConfirmNewSchedule.xaml
    /// </summary>
    public partial class frmConfirmNewSchedule : Window
    {
        PetUniverseUser _user;
        ScheduleVM _schedule;

        /// <summary>
        /// Creator: Jordan Lindo
        /// Created: 4/23/2020
        /// Approver:
        /// 
        ///  Confirm schedule constructor.
        /// </summary>
        /// <remarks>
        /// Updater: NA
        /// Updated: NA
        /// Update: NA
        /// 
        /// </remarks>
        /// <param name="user"></param>
        /// <param name="schedule"></param>
        public frmConfirmNewSchedule(PetUniverseUser user, ScheduleVM schedule)
        {
            InitializeComponent();
            _user = user;
            _schedule = schedule;
            setDG();
        }

        /// <summary>
        /// Creator: Jordan Lindo
        /// Created: 4/23/2020
        /// Approver:
        /// 
        /// Method for filling the datagrid.
        /// </summary>
        /// <remarks>
        /// Updater: NA
        /// Updated: NA
        /// Update: NA
        /// 
        /// </remarks>
        private void setDG()
        {
            List<ShiftUserVM> shifts = _schedule.ScheduleLines;
            foreach (ShiftUserVM shift in shifts)
            {
                shift.DateString = shift.ShiftDate.ToShortDateString();
            }
            dgScheduleApproval.ItemsSource = shifts;
        }

        /// <summary>
        /// Creator: Jordan Lindo
        /// Created: 4/23/2020
        /// Approver:
        /// 
        /// Schedule manager constructor.
        /// </summary>
        /// <remarks>
        /// Updater: NA
        /// Updated: NA
        /// Update: NA
        /// 
        /// </remarks>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void btnAccept_Click(object sender, RoutedEventArgs e)
        {
            _schedule.CreatingUserID = _user.PUUserID;
            _schedule.CreatorName = _user.LastName + ", " + _user.FirstName;
            this.DialogResult = true;

        }

        /// <summary>
        /// Creator: Jordan Lindo
        /// Created: 4/23/2020
        /// Approver:
        /// 
        /// Mehtod for making the datagrid presentable.
        /// </summary>
        /// <remarks>
        /// Updater: NA
        /// Updated: NA
        /// Update: NA
        /// 
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void dgScheduleApproval_AutoGeneratedColumns(object sender, EventArgs e)
        {
            dgScheduleApproval.Columns.RemoveAt(4);
            dgScheduleApproval.Columns.RemoveAt(4);
            dgScheduleApproval.Columns.RemoveAt(4);
            dgScheduleApproval.Columns.RemoveAt(4);
            dgScheduleApproval.Columns.RemoveAt(4);
            dgScheduleApproval.Columns[0].Header = "Date";
            dgScheduleApproval.Columns[1].Header = "Employee Name";
            dgScheduleApproval.Columns[2].Header = "Start";
            dgScheduleApproval.Columns[3].Header = "End";
            dgScheduleApproval.Columns[4].Header = "Role";
            dgScheduleApproval.Columns[0].Width = 80;
            dgScheduleApproval.Columns[2].Width = 70;
            dgScheduleApproval.Columns[3].Width = 70;
            dgScheduleApproval.Columns[4].Width = 80;


        }

        /// <summary>
        /// Creator: Jordan Lindo
        /// Created: 4/23/2020
        /// Approver:
        /// 
        /// Button for declining a generated schedule.
        /// </summary>
        /// <remarks>
        /// Updater: NA
        /// Updated: NA
        /// Update: NA
        /// 
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void btnDecline_Click(object sender, RoutedEventArgs e)
        {
            this.DialogResult = false;
        }
    }
}
