using DataTransferObjects;
using LogicLayer;
using LogicLayerInterfaces;
using PresentationUtilityCode;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Windows;
using System.Windows.Controls;

namespace WPFPresentationLayer.PersonnelPages
{
    /// <summary>
    /// Interaction logic for ViewAllRoles.xaml
    /// </summary>
    public partial class ViewAllRoles : Page
    {

        private IDepartmentManager _departmentManager = null;
        private IERoleManager _eRoleManager = null;

        bool _addMode = false;
        private ERole _eRole = null;


        public ViewAllRoles()
        {

            InitializeComponent();
            _departmentManager = new DepartmentManager();
            _eRoleManager = new ERoleManager();
        }

        /// <summary>
        /// Creator: Chase Schulte
        /// Created: 02/13/2020
        /// Approver: Kaleb Bachert
        /// 
        /// Populate the role list upon selecting view roles tab
        /// </summary>
        ///
        /// <remarks>
        /// Updater 
        /// Updated:
        /// Update: 
        /// </remarks>
        /// <param name="sender"></param>
        /// <param name="e"></param>

        private void RefreshERole()
        {
            try
            {
                dgERoleList.ItemsSource = _eRoleManager.RetrieveERolesByActive((bool)chkRoleActive.IsChecked);
            }
            catch (Exception ex)
            {
                WPFErrorHandler.ErrorMessage(ex.Message);
            }
        }

        /// <summary>
        /// Creator: Chase Schulte
        /// Created: 02/13/2020
        /// Approver: Kaleb Bachert
        /// 
        /// Rename column names
        /// </summary>
        ///
        /// <remarks>
        /// Updater: Chase Schulte 
        /// Updated: Removes all user inheritence
        /// Update: 04/10/2020
        /// Approver: Kaleb Bachert
        /// </remarks>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void DgERoleList_AutoGeneratedColumns(object sender, EventArgs e)
        {
            dgERoleList.Columns.RemoveAt(16);
            dgERoleList.Columns.RemoveAt(15);
            dgERoleList.Columns.RemoveAt(14);
            dgERoleList.Columns.RemoveAt(13);
            dgERoleList.Columns.RemoveAt(12);
            dgERoleList.Columns.RemoveAt(11);
            dgERoleList.Columns.RemoveAt(10);
            dgERoleList.Columns.RemoveAt(9);
            dgERoleList.Columns.RemoveAt(8);
            dgERoleList.Columns.RemoveAt(7);
            dgERoleList.Columns.RemoveAt(6);
            dgERoleList.Columns.RemoveAt(5);
            dgERoleList.Columns.RemoveAt(4);
            dgERoleList.Columns.RemoveAt(3);
            dgERoleList.Columns.RemoveAt(3);
            dgERoleList.Columns.RemoveAt(3);
            dgERoleList.Columns.RemoveAt(3);
            dgERoleList.Columns.RemoveAt(3);
            dgERoleList.Columns[0].Header = "Role";
            dgERoleList.Columns[1].Header = "Department";
            dgERoleList.Columns[2].Header = "Description";

        }

        /// <summary>
        /// Creator: Chase Schulte
        /// Created: 02/13/2020
        /// Approver: Jordan Lindo
        /// 
        /// Open a role for view or editing
        /// </summary>
        ///
        /// <remarks>
        /// Updater: Chase Schulte
        /// Updated: 03/04/2020
        /// Update: Added messagebox when attempting to change a null selectedItem
        /// </remarks>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void BtnOpenERole_Click(object sender, RoutedEventArgs e)
        {
            if (dgERoleList.SelectedItem != null)
            {
                try
                {
                    ERole selectedERole = (ERole)dgERoleList.SelectedItem;
                    _eRole = selectedERole;
                    //Populate combo box with current values
                    cmbDepartmentID.Text = selectedERole.DepartmentID;
                }
                catch (Exception ex)
                {
                    WPFErrorHandler.ErrorMessage(ex.Message);
                }
                gridEditERoles.Visibility = Visibility.Visible;
                _addMode = false;
                updateMode();
            }
            else
            {
                WPFErrorHandler.ErrorMessage("Please select a Role");
            }
        }

        /// <summary>
        /// Creator: Chase Schulte
        /// Created: 02/13/2020
        /// Approver: Kaleb Bachert
        /// 
        /// Helper method to get view ready for update
        /// </summary>
        ///
        /// <remarks>
        /// Updater 
        /// Updated:
        /// Update: 
        /// </remarks>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void updateMode()
        {
            txtERoleID.IsReadOnly = true;
            txtDescription.IsReadOnly = false;
            cmbDepartmentID.IsEnabled = true;
            chkActive.IsEnabled = true;
            btnSave.Visibility = Visibility.Visible;
            btnBackRole.Visibility = Visibility.Visible;
            btnNextRole.Visibility = Visibility.Visible;
            populateERoleText();
            disableViewERoles();
        }
        /// <summary>
        /// Creator: Chase Schulte
        /// Created: 03/03/2020
        /// Approver: Jordan Lindo
        /// 
        /// Helper method to get view ready for viewing
        /// </summary>
        ///
        /// <remarks>
        /// Updater 
        /// Updated:
        /// Update: 
        /// </remarks>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void viewMode()
        {
            btnSave.Visibility = Visibility.Collapsed;
            txtERoleID.IsReadOnly = true;
            txtDescription.IsReadOnly = true;
            cmbDepartmentID.IsEnabled = false;
            chkActive.IsEnabled = false;
            btnBackRole.Visibility = Visibility.Visible;
            btnNextRole.Visibility = Visibility.Visible;
            populateERoleText();
            disableViewERoles();
        }
        /// <summary>
        /// Creator: Chase Schulte
        /// Created: 02/13/2020
        /// Approver: Jordan Lindo
        /// 
        /// Helper method to get view ready for create
        /// </summary>
        ///
        /// <remarks>
        /// Updater: Chase Schulte
        /// Updated: 03/04/2020
        /// Update: Added messagebox when attempting to change a null selectedItem
        /// </remarks>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void createMode()
        {
            depopulateERoleText();
            txtERoleID.IsReadOnly = false;
            txtDescription.IsReadOnly = false;
            cmbDepartmentID.IsEnabled = true;
            btnSave.Visibility = Visibility.Visible;
            chkActive.IsChecked = true;
            chkActive.IsEnabled = false;
            _eRole = null;
            btnBackRole.Visibility = Visibility.Hidden;
            btnNextRole.Visibility = Visibility.Hidden;
            disableViewERoles();
            cmbDepartmentID.SelectedIndex = 0;
        }

        /// <summary>
        /// Creator: Chase Schulte
        /// Created: 02/13/2020
        /// Approver: Jordan Lindo
        /// 
        /// Helper method disable view all
        /// </summary>
        ///
        /// <remarks>
        /// Updater: Chase Schulte
        /// Updated: 03/04/2020
        /// Update: Added hide btnViewERole
        /// </remarks>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void disableViewERoles()
        {
            lblTitle.Visibility = Visibility.Hidden;
            btnViewERole.Visibility = Visibility.Collapsed;
            btnAddERole.Visibility = Visibility.Collapsed;
            btnDeleteERole.Visibility = Visibility.Collapsed;
            btnOpenRole.Visibility = Visibility.Collapsed;
            dgERoleList.Visibility = Visibility.Collapsed;
            lblActive.Visibility = Visibility.Collapsed;
            chkRoleActive.Visibility = Visibility.Collapsed;
        }
        /// <summary>
        /// Creator: Chase Schulte
        /// Created: 02/13/2020
        /// Approver: Jordan Lindo
        /// 
        /// Helper method to enable view all
        /// </summary>
        ///
        /// <remarks>
        /// Updater: Chase Schulte
        /// Updated: 03/04/2020
        /// Update: Added show btnViewERole
        /// </remarks>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void enableViewERoles()
        {
            lblTitle.Visibility = Visibility.Visible;
            btnAddERole.Visibility = Visibility.Visible;
            btnDeleteERole.Visibility = Visibility.Collapsed;
            btnOpenRole.Visibility = Visibility.Visible;
            btnViewERole.Visibility = Visibility.Visible;
            dgERoleList.Visibility = Visibility.Visible;
            lblActive.Visibility = Visibility.Visible;
            chkRoleActive.Visibility = Visibility.Visible;
        }

        /// <summary>
        /// Creator: Chase Schulte
        /// Created: 02/13/2020
        /// Approver: Kaleb Bachert
        /// 
        /// Add a new Role
        /// </summary>
        ///
        /// <remarks>
        /// Updater 
        /// Updated:
        /// Update: 
        /// </remarks>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void BtnAddERole_Click(object sender, RoutedEventArgs e)
        {
            _addMode = true;
            createMode();
            gridEditERoles.Visibility = Visibility.Visible;
        }

        /// <summary>
        /// Creator: Chase Schulte
        /// Created: 02/13/2020
        /// Approver: Jordan Lindo
        /// 
        /// Delete a role
        /// </summary>
        ///
        /// <remarks>
        /// Updater: Chaser Schulte 
        /// Updated: 02/28/2020
        /// Update: Delete can only occur on in-active roles
        /// </remarks>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void BtnDeleteERole_Click(object sender, RoutedEventArgs e)
        {
            if (dgERoleList.SelectedItem != null)
            {
                ERole selectedERole = (ERole)dgERoleList.SelectedItem;
                if (selectedERole.EActive == true)
                {
                    WPFErrorHandler.ErrorMessage("Can't delete an active Role");
                    return;
                }
                var deleteERole = MessageBox.Show("Are you sure you want to delete " + selectedERole.ERoleID, "Confirm Delete", MessageBoxButton.YesNo, MessageBoxImage.Warning);
                if (deleteERole == MessageBoxResult.Yes)
                {
                    try
                    {
                        _eRoleManager.DeleteERole(selectedERole.ERoleID);
                        RefreshERole();
                    }
                    catch (Exception ex)
                    {
                        WPFErrorHandler.ErrorMessage(ex.Message);
                    }
                }
            }
            else
            {
                WPFErrorHandler.ErrorMessage("Please select a role");
            }
        }

        /*****************         Edit/View ERole            ******************/


        /// <summary>
        /// Creator: Chase Schulte
        /// Created: 02/13/2020
        /// Approver: Kaleb Bachert
        /// 
        /// Save information into DB
        /// </summary>
        ///
        /// <remarks>
        /// Updater 
        /// Updated:
        /// Update: 
        /// </remarks>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void BtnSave_Click(object sender, RoutedEventArgs e)
        {
            var deleteERole = MessageBox.Show("Is the entered info coreect", "", MessageBoxButton.YesNo, MessageBoxImage.Question);
            if (deleteERole == MessageBoxResult.Yes)
            {
                string eRoleID = txtERoleID.Text;
                string DepartmentID = cmbDepartmentID.Text;
                string description = txtDescription.Text;
                if (!eRoleID.checkERoleID())
                {
                    WPFErrorHandler.ErrorMessage("You must a enter a vaild Role");
                    txtERoleID.Focus();
                    return;
                }
                if (!DepartmentID.checkDepartmentID())
                {
                    WPFErrorHandler.ErrorMessage("You must a enter a vaild Department");
                    cmbDepartmentID.Focus();
                    return;
                }
                if (!description.checkDescription())
                {
                    WPFErrorHandler.ErrorMessage("You must a enter a vaild Descirption");
                    txtDescription.Focus();
                    return;
                }

                ERole newERole = new ERole()
                {
                    ERoleID = txtERoleID.Text,
                    Description = txtDescription.Text,
                    DepartmentID = cmbDepartmentID.Text

                };

                if (_addMode == true)
                {
                    try
                    {
                        if (_eRoleManager.AddERole(newERole))
                        {
                            RefreshERole();
                            gridEditERoles.Visibility = Visibility.Collapsed;
                            enableViewERoles();
                        }
                    }
                    catch (Exception ex)
                    {
                        WPFErrorHandler.ErrorMessage(ex.Message);
                    }
                }
                else if (_addMode == false)
                {
                    try
                    {
                        if (_eRoleManager.EditERole(_eRole, newERole))
                        {
                            RefreshERole();
                            gridEditERoles.Visibility = Visibility.Collapsed;
                            enableViewERoles();
                        }
                    }
                    catch (Exception ex)
                    {
                        WPFErrorHandler.ErrorMessage(ex.Message);
                    }
                }
            }
        }
        /// <summary>
        /// Creator: Chase Schulte
        /// Created: 02/13/2020
        /// Approver: Kaleb Bachert
        /// 
        /// Cancel frm and do not save elements
        /// </summary>
        ///
        /// <remarks>
        /// Updater 
        /// Updated:
        /// Update: 
        /// </remarks>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void BtnCancel_Click(object sender, RoutedEventArgs e)
        {
            gridEditERoles.Visibility = Visibility.Collapsed;
            enableViewERoles();
        }
        /// <summary>
        /// Creator: Chase Schulte
        /// Created: 02/13/2020
        /// Approver: Kaleb Bachert
        /// 
        /// Activate or deactivate a role
        /// </summary>
        ///
        /// <remarks>
        /// Updater 
        /// Updated:
        /// Update: 
        /// </remarks>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void ChkActive_Click(object sender, RoutedEventArgs e)
        {
            try
            {
                {
                    if (!(bool)chkActive.IsChecked)
                    {
                        _eRoleManager.DeactivateERole(_eRole.ERoleID);
                        RefreshERole();

                    }
                    else if ((bool)chkActive.IsChecked)
                    {
                        _eRoleManager.ActivateERole(_eRole.ERoleID);
                        RefreshERole();
                    }
                }

            }
            catch (Exception ex)
            {
                WPFErrorHandler.ErrorMessage(ex.Message);
            }
        }

        /// <summary>
        /// Creator: Chase Schulte
        /// Created: 02/13/2020
        /// Approver: Kaleb Bachert
        /// 
        /// Get next role in database
        /// </summary>
        ///
        /// <remarks>
        /// Updater 
        /// Updated:
        /// Update: 
        /// </remarks>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void BtnNextERole_Click(object sender, RoutedEventArgs e)
        {
            List<ERole> eRoles = null;
            //get current eRole, search, by comparing all eRoles in a array via _eRoleManager, then get previous. Ask user if they are sure as all changes will go unsaved
            try
            {
                eRoles = _eRoleManager.RetrieveERolesByActive((bool)chkRoleActive.IsChecked);
            }
            catch (Exception ex)
            {
                WPFErrorHandler.ErrorMessage(ex.Message);
            }
            ERole eRole = new ERole();
            eRole.ERoleID = txtERoleID.Text;
            eRole.DepartmentID = cmbDepartmentID.Text;
            eRole.Description = txtDescription.Text;
            eRole.EActive = (bool)chkActive.IsChecked;
            int eRoleIndex = 0;
            //Find current eRole
            eRoleIndex = findMatchingID(eRoles, eRoleIndex);
            eRoleIndex++;
            //Make sure eRole is unchanged, else ask user if sure
            if (!_eRole.Description.Equals(eRole.Description) || !_eRole.DepartmentID.Equals(eRole.DepartmentID))
            {
                var goForwardERole = MessageBox.Show("You will lose all unsaved progress", "Are you sure?", MessageBoxButton.YesNo, MessageBoxImage.Question);
                if (goForwardERole == MessageBoxResult.Yes)
                {
                    //Check if previous eRole is null
                    if (eRoleIndex.checkERoleIndex(eRoles))
                    {
                        //If null, go to first entry
                        _eRole = eRoles.First();
                        populateERoleText();
                    }
                    else
                    {
                        _eRole = eRoles.ElementAt(eRoleIndex);
                        populateERoleText();
                    }
                }
                else
                {
                    return;
                }
            }
            else
            {
                //Check if previous eRole is null
                if (eRoleIndex.checkERoleIndex(eRoles))
                {
                    //If null, go to last entry
                    _eRole = eRoles.First();
                    populateERoleText();
                }
                else
                {
                    _eRole = eRoles.ElementAt(eRoleIndex);
                    populateERoleText();
                }

            }
        }

        /// <summary>
        /// Creator: Chase Schulte
        /// Created: 02/13/2020
        /// Approver: Kaleb Bachert
        /// 
        /// Get previous role in database
        /// </summary>
        ///
        /// <remarks>
        /// Updater 
        /// Updated:
        /// Update: 
        /// </remarks>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void BtnBackERole_Click(object sender, RoutedEventArgs e)
        {

            List<ERole> eRoles = null;
            //get current eRole, search, by comparing all eRoles in a array via _eRoleManager, then get previous. Ask user if they are sure as all changes will go unsaved
            try
            {
                eRoles = _eRoleManager.RetrieveERolesByActive((bool)chkRoleActive.IsChecked);
            }
            catch (Exception ex)
            {
                WPFErrorHandler.ErrorMessage(ex.Message);
            }
            ERole eRole = new ERole();
            eRole.ERoleID = txtERoleID.Text;
            eRole.DepartmentID = cmbDepartmentID.Text;
            eRole.Description = txtDescription.Text;
            eRole.EActive = (bool)chkActive.IsChecked;
            int eRoleIndex = 0;
            //Find current eRole
            eRoleIndex = findMatchingID(eRoles, eRoleIndex);
            eRoleIndex--;
            //Make sure eRole is unchanged, else ask user if sure
            if (!_eRole.Description.Equals(eRole.Description) || !_eRole.DepartmentID.Equals(eRole.DepartmentID))
            {
                var goBackERole = MessageBox.Show("You will lose all unsaved progress", "Are you sure?", MessageBoxButton.YesNo, MessageBoxImage.Question);
                if (goBackERole == MessageBoxResult.Yes)
                {
                    //Check if previous eRole is null
                    if (eRoleIndex.checkERoleIndex(eRoles))
                    {
                        //If null, go to last entry
                        _eRole = eRoles.Last();
                        populateERoleText();
                    }
                    else
                    {
                        _eRole = eRoles.ElementAt(eRoleIndex);
                        populateERoleText();
                    }
                }
                else
                {
                    return;
                }
            }
            else
            {
                //Check if previous eRole is null
                if (eRoleIndex.checkERoleIndex(eRoles))
                {
                    //If null, go to last entry
                    _eRole = eRoles.Last();
                    populateERoleText();
                }
                else
                {
                    _eRole = eRoles.ElementAt(eRoleIndex);
                    populateERoleText();
                }

            }
        }

        /// <summary>
        /// Creator: Chase Schulte
        /// Created: 02/13/2020
        /// Approver: Kaleb Bachert
        /// 
        /// Find matching ID
        /// </summary>
        ///
        /// <remarks>
        /// Updater 
        /// Updated:
        /// Update: 
        /// </remarks>
        /// <param name="eRoles"></param>
        /// <param name="eRoleIndex"></param>
        /// <returns></returns>
        private int findMatchingID(List<ERole> eRoles, int eRoleIndex)
        {
            foreach (var r in eRoles)
            {
                if (r.ERoleID.checkStringIsEqual(txtERoleID.Text))
                {
                    eRoleIndex = eRoles.IndexOf(r);
                    break;
                }
            }
            return eRoleIndex;
        }

        /// <summary>
        /// Creator: Chase Schulte
        /// Created: 02/13/2020
        /// Approver: Kaleb Bachert
        /// 
        /// Helper method to repopulate input fields to match _eRole object
        /// </summary>
        ///
        /// <remarks>
        /// Updater 
        /// Updated:
        /// Update: 
        /// </remarks>
        private void populateERoleText()
        {
            txtERoleID.Text = _eRole.ERoleID;
            txtDescription.Text = _eRole.Description;
            cmbDepartmentID.Text = _eRole.DepartmentID;
            chkActive.IsChecked = _eRole.EActive;
        }

        /// <summary>
        /// Creator: Chase Schulte
        /// Created: 02/13/2020
        /// Approver: Kaleb Bachert
        /// 
        /// Helper method to un-populate input fields to match _eRole object
        /// </summary>
        ///
        /// <remarks>
        /// Updater:
        /// Updated:
        /// Update: 
        /// </remarks>
        private void depopulateERoleText()
        {
            txtERoleID.Text = "";
            txtDescription.Text = "";
            cmbDepartmentID.Text = "";
        }
        /// <summary>
        /// Creator: Chase Schulte
        /// Created: 02/28/2020
        /// Approver: Kaleb Bachert
        /// 
        /// Get page ready/refreshed
        /// </summary>
        ///
        /// <remarks>
        /// Updater:
        /// Updated:
        /// Update: 
        /// </remarks>
        /// <summary>
        /// 
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void Page_Loaded(object sender, RoutedEventArgs e)
        {
            RefreshERole();
            gridEditERoles.Visibility = Visibility.Collapsed;
            enableViewERoles();
            depopulateERoleText();
            //Populate combo boxes
            try
            {
                List<string> departments = new List<string>();
                foreach (var item in _departmentManager.RetrieveAllDepartments())
                {
                    departments.Add(item.DepartmentID);
                }

                cmbDepartmentID.ItemsSource = departments;
            }
            catch (Exception ex)
            {
                WPFErrorHandler.ErrorMessage(ex.Message);
            }
        }
        /// <summary>
        /// Creator: Chase Schulte
        /// Created: 02/28/2020
        /// Approver: Kaleb Bachert
        /// 
        /// sort roles by active/inactive
        /// </summary>
        ///
        /// <remarks>
        /// Updater:
        /// Updated:
        /// Update: 
        /// </remarks>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void ChkRoleActive_Click(object sender, RoutedEventArgs e)
        {
            RefreshERole();
        }
        /// <summary>
        /// Creator: Chase Schulte
        /// Created: 03/03/2020
        /// Approver: Jordan Lindo
        /// 
        /// view roles but not edit
        /// </summary>
        ///
        /// <remarks>
        /// Updater: Chase Schulte
        /// Updated: 03/04/2020
        /// Update: Added messagebox when attempting to change a null selectedItem
        /// </remarks>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void BtnViewRole_Click(object sender, RoutedEventArgs e)
        {
            if (dgERoleList.SelectedItem != null)
            {
                try
                {
                    ERole selectedERole = (ERole)dgERoleList.SelectedItem;
                    _eRole = selectedERole;
                    //Populate combo box with current values
                    cmbDepartmentID.Text = selectedERole.DepartmentID;
                }
                catch (Exception ex)
                {
                    WPFErrorHandler.ErrorMessage(ex.Message);
                }
                gridEditERoles.Visibility = Visibility.Visible;
                _addMode = false;
                viewMode();
            }
            else
            {
                WPFErrorHandler.ErrorMessage("Please select a Role");
            }
        }
    }
}
